### ISSUE TITLE
Review Requested

### ISSUE THREAD

**Issue by Marinlestylo** [AMT-TEAM07/PictureLabelizer#20]
@NicolasGlassey

https://github.com/AMT-TEAM07/PictureLabelizer/commit/544e40cda6b531423af86a5759e9058a67f5d673

**Comment by NicolasGlassey** [comment]
@Marinlestylo @Lazzzer 

Bonsoir Messieurs,

J'ai pu exécuter votre livrable sur AWS. Parfait !

La documentation est super claire !

Bonne soirée et à demain.
Nicolas
