### ISSUE TITLE
Refactor du code suite à la Pull request

### ISSUE THREAD

**Issue by Marinlestylo** [AMT-TEAM07/PictureLabelizer#23]
@NicolasGlassey 
Nous avons merge votre pull request après avoir fait toutes les modifications demandées.
Vous pouvez trouver ces modifications ici : [d3ea10f3bec17ed492dacfd93cdca5a4261c1336](https://github.com/AMT-TEAM07/PictureLabelizer/commit/d3ea10f3bec17ed492dacfd93cdca5a4261c1336)

**Comment by NicolasGlassey** [comment]
@Marinlestylo  @Lazzzer 

Les remarques ont été prises en compte !
